OWORLD/WEB/Django/mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LastestPostFeed
app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('',views.        PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/',views.post_share,name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/',LastestPostFeed(),name='post_feed'), # 订阅
]



# wget http://nginx.org/download/nginx-1.15.10.tar.gz

OWORLD/WEB/Django/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
sitemaps = {'posts': PostSitemap,}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml/',sitemap,{'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

OWORLD/WEB/Django/mysite/blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# 增加模型管理器 （默认objects）
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    objects = models.Manager()  # 默认的管理器
    published = PublishedManager()  # 自定义管理器
    tags = TaggableManager()    # django-taggit 标签模板

    STATUS_CHOICES = (('draft', 'Draft'), ('published', 'Published'))
    title = models.CharField(max_length=250)
    # unique_for_date 通过日期和简称可以找到唯一的一篇文章（或者找不到)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    # on_delete参数表示删除外键关联的内容时候的操作  
    #   CASCADE意味着如果删除一个作者，将自动删除所有与这个作者关联的文章
    # related_name参数设置了从User到Post的反向关联关系，用blog_posts为这个反向关联关系命名
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now())
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year, self.publish.month, self.publish.day, self.slug])

    # 默认按照发布时间的逆序将查询结果排序
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

# 评论系统
class Comment(models.Model):
    # 将评论和文字进行关联  
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    # auto_now_add表示当创建一行数据的时候，自动用创建数据的时间填充。
    created = models.DateTimeField(auto_now_add=True)
    # auto_now表示每次更新数据的时候，都会用当前的时间填充该字段。
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) # 用于手工关闭不恰当的评论

    # 根据创建时间结果排序
    class Meta:
        ordering = ('created',)

OWORLD/WEB/Django/mysite/blog/forms.py
from django import forms

# 邮件的功能里，采用继承forms.Form类的方式，自行编写各个字段创建了一个表单。
# Django对于表单有两个类：Form和ModelForm。
# 这次我们使用ModelForm动态的根据Comment模型生成表单


#save()方法仅对ModelForm生效，因为Form类没有关联到任何数据模型。
class EmailPostForm(forms.Form):
    # 每个字段都有一个默认的widget参数决定该字段被渲染成的HTML元素类型
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    # required=False表示该字段可以没有任何值
    comments = forms.CharField(required=False, widget=forms.Textarea)

from .models import Comment

class CommentForm(forms.ModelForm):
    
    # 依据模型创建表单，只需要在Meta类中指定基于哪个类即可。
    # Django会自动内省该类然后创建对应的表单。
    # 可以显示的通过Meta类中的fields属性指定需要创建表单元素的字段
    class Meta:
        model = Comment
        # fields = '__all__'
        fields  = ('name','email','body')

OWORLD/WEB/Django/mysite/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from .models import Post,Comment
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

def post_list(request,tag_slug=None):
    # posts = Post.published.all()
    # return render(request, 'blog/post/list.html', {'posts': posts})
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    # 使用django 自带分页
    paginator = Paginator(object_list,2) # 每页显示三篇文章
    page = request.GET.get('page') # django自带分页参数
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # 如果page参数非整数返回第一页
        posts  = paginator.page(1)
    except EmptyPage:
        # 如果超出总页数返回最后一页
        posts = paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'page':page,'posts':posts,'tag':tag})

from .forms import CommentForm

def tk(request):
    import os 
    print('###:',os.getcwd())
    return render(request,'k/index.html')

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status="published", publish__year=year, publish__month=month,
                             publish__day=day)

    new_comment =  None                         
    # 通过外键对post对象执行查询获得所需的QuerySet()
    comments = post.comments.filter(active=True)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():     # 验证表单数据
            # 通过表单直接创建数据对象 不提交到数据库
            new_comment = comment_form.save(commit=False)
            # 设置外键为当前文章
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()       
    
        # 显示相近Tag的文章列表
    post_tags_ids = post.tags.values_list('id',flat=True)
    similar_tags = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_tags.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    
    # values_list方法返回指定的字段的值构成的元组，通过指定flat=True，让其结果变成一个列表比如[1, 2, 3, ...]
    # 选出所有包含上述标签的文章并且排除当前文章
    # 使用Count对每个文章按照标签计数，并生成一个新字段same_tags用于存放计数的结果
    # 按照相同标签的数量，降序排列结果，然后截取前四个结果作为最终传入模板的数据对象。

    return render(request, 'blog/post/detail.html', {'post': post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form,'similar_posts':similar_posts})

from  django.views.generic import ListView
class PostListView(ListView):
    # Django内置的ListView返回的变量名称叫做page_obj 修改模板T
    # model = Post    # 可用queryset = Post.published.all() 替代
    queryset = Post.published.all()
    print (queryset)
    context_object_name='posts'    # 如果不设置context_object_name参数，默认的变量名称是object_list
    paginate_by = 2 # 每页的显示文章数
    template_name = 'blog/post/list.html'

from .forms import EmailPostForm
def post_share(request,post_id):
    post = get_object_or_404(Post,id=post_id,status='published')
    sent = False
    if request.method=='POST':
        # 表单提交
        form = EmailPostForm(request.POST)
        if form.is_valid(): # 验证表单数据是否有效
    #   如果表单验证成功，可以通过form.cleaned_data属性访问表单内所有通过验证的数据，这个属性类似于一个字典，包含字段名与值构成的键值对。
    #   如果表单验证失败，form.cleaned_data只会包含通过验证的数据。
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, '1255381744@qq.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,'blog/post/share.html',{'form':form,'post':post,'sent':sent})

OWORLD/WEB/Django/mysite/blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog. I've written {% total_posts %} posts so far.</p>
        <h3>Latest posts</h3>
        {% show_latest_posts 3 %}

        <h3>Most commented posts</h3>
        {% get_most_comment_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% endfor %}
        </ul>
        <p><a href='{% url "blog:post_feed" %}'>Subscribe to my RSS feed</a></p>
    </div>
</body>
</html> 

OWORLD/WEB/Django/mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}
{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
    Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>
    
    <!-- 推荐文章(相似) -->
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{total_comments}} comment {{total_comments|pluralize}}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
        {% empty %}
            <p>There are no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
    <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
        {{ comment_form.as_p }}
            {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

OWORLD/WEB/Django/mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

OWORLD/WEB/Django/mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %} 
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <!-- {{ post.get_absolute_url }} -->
            <a href="{{ post.get_absolute_url }}">
            <!-- <a href="/blog/{{post.publish.year}}/{{post.publish.month}}/{{post.publish.day}}/{{post.slug}}/"> -->
                {{ post.title }}
            </a>
            <p class="tags">Tags: 
                {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{tag.name}}</a>
                {% if not forloop.last %}, {% endif %}
                {% endfor %}
                <!-- {{ post.tags.all|join:", " }} -->
            </p>
        </h2>
        <p class="date">
        Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
        <!-- truncatewords_html过滤器不会截断未闭合的HTML标签。 -->
    {% endfor %}
    {% include 'paginator.html' with page=posts %}
    {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
{% endblock %}

OWORLD/WEB/Django/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="post">
        <!-- 使用as_p方法将表单中的所有元素以<p>元素的方式展现出来 -->
        {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

OWORLD/WEB/Django/mysite/blog/templates/paginator.html
<div    class="paginator">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{page.previous_page_number}}">
            Previous
        </a>
        {% endif %}
        <span class="current">
            Page {{page.number}} of {{page.paginator.num_pages}}.
        </span>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">
                Next
            </a>
        {% endif %}
    </span>
</div>